### ISSUE TITLE
Unavailable position-based subscript setter crashes on runtime

### ISSUE THREAD

**Issue by Thomvis** [pointfreeco/swift-identified-collections#14]
After upgrading from TCA's `IdentifiedArray` to the version in this repo (`0.1.1`), my app is crashing in places where it [used](https://github.com/Thomvis/Construct/blob/de78e0faa047c09ff5ab6b8826444b8fa40d10b7/UnitTests/AppStoreScreenshotTests.swift#L260) the position-based subscript setter.

There's a `@available` annotation in the [code](https://github.com/pointfreeco/swift-identified-collections/blob/main/Sources/IdentifiedCollections/IdentifiedArray/IdentifiedArray+Collection.swift#L19), but that doesn't show up (at least not in Xcode 12.5). It's the `fatalError` in the setter that hits.

The weird thing is that the error did show up in another [place in my code](https://github.com/Thomvis/Construct/blob/de78e0faa047c09ff5ab6b8826444b8fa40d10b7/UnitTests/AppStoreScreenshotTests.swift#L330).

I think it's unfortunate that has become a runtime issue, but I'm not sure how to fix that. I'm also not sure why the setter can't be implemented. I can live without it (I only use it in tests), but it was convenient to have.

**Comment by Thomvis** [comment]
Looks like this comes from a restriction of the underlying `OrderedDictionary` offset-based subscript. That one doesn't have a setter either. However, the [docs](https://github.com/apple/swift-collections/blob/main/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift#L292) seems to imply it should be used for in-place mutation...

**Comment by Thomvis** [comment]
I wrote a very naive implementation that works in my app: https://github.com/Thomvis/swift-identified-collections/commit/f6561f9ef2feb179b64c8aed7a6ee0b7570d8949.

Do you think something like this could be added to the library?

**Comment by stephencelis** [comment]
@Thomvis Dang, yeah I hit that exact issue. It appears to be a compiler bug 😞

We eliminated the index-based setter because we think it opens up the opportunity to create invalid collections, e.g. if you have an element at 0 identifying as `"deadbeef"` and then you try to insert another element at 1 that also identifies as `"deadbeef"`. Swift Collections' `OrderedSet` type has the same design.

So, instead of adding `_modify` to the subscript, can you use the `id`-based subscript instead? For example:

```swift
mage.resources[id: mage.resources[0].id].used = 1
```

I think what we'll probably want to do in the library is remove the deprecation entirely, so that the compiler can catch the issue. It's a bit of a bummer that we can't offer a better migration path, but this compiler bug is out of our control!

**Comment by stephencelis** [comment]
@Thomvis we plan on removing this setter in #15, but wanted to make sure you could still mutate things via the other subscript.

**Comment by Thomvis** [comment]
@stephencelis yes, that works. I’ll probably end up creating a “idPosition” subscript helper in my test target to make it a bit easier. In all/most other cases, using the mutable position-based subscript was a mediocre choice anyway. Thanks!

**Comment by stephencelis** [comment]
Fixed in #15.
