### ISSUE TITLE
Guidance for bulk insertion?

### ISSUE THREAD

**Issue by jessegrosjean** [pointfreeco/swift-identified-collections#4]
I don't see any API for bulk insertion.

Am I missing, or is that by design?

Without such an API it seems like inserting many items at start could get very expensive?

The mostly untested workaround that I'm using is to append the items to insert at the end and then using `move(fromOffsets:toOffset:)` to get them into correct position. Does that seem reasonable?

**Comment by stephencelis** [comment]
This is intentional, and is similar to the behavior of `OrderedSet`. We try to document it here:

https://github.com/pointfreeco/swift-identified-collections/blob/6e21c97fe5c50d3e69214891215d986a5705143d/Sources/IdentifiedCollections/IdentifiedArray/IdentifiedArray.swift#L235

Things should remain performant when inserting a lot of items by calling `reserveCapacity(count + insertions.count)` before doing the work.
